# Build workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Validate wrapper to prevent potential supply chain attack
  gradle-wrapper-validation:
    runs-on: ubuntu-latest

    name: Validate Gradle wrapper

    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v5

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11', '21' ]

    name: Java ${{ matrix.Java }} build

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v5

      # Set JDK
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # Build
      - name: Build with Gradle
        run: ./gradlew build

      # Upload test artifact
      - name: Upload test output
        uses: actions/upload-artifact@v5
        if: ${{ failure() }}
        with:
          name: test-output-${{ matrix.java }}
          path: |
            build/reports/
          retention-days: 15
          overwrite: true

  testOn8:
    runs-on: ubuntu-latest

    name: Test on Java 8

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      # Run tests with Java 8
      - name: Test with Java 8
        run: ./gradlew testOn8
